import type { TranslateFn } from '../services/i18n';

export function createDummyTranslate(): TranslateFn {
  const translations: Record<string, string> = {
    'navigation.dashboard': 'Dashboard',
    'navigation.collections': 'Collections',
    'navigation.content': 'Content',
    'navigation.media': 'Media',
    'navigation.users': 'Users',
    'navigation.plugins': 'Plugins',
    'navigation.settings': 'Settings',
    'navigation.profile': 'Profile',
    'navigation.myProfile': 'My Profile',
    'navigation.signOut': 'Sign Out',
    'navigation.closeMenu': 'Close menu',
    'navigation.openNavigation': 'Open navigation',
    'navigation.closeNavigation': 'Close navigation',
    'migrations.pendingDetected': '{count} pending database migration(s) detected',
    'migrations.runCommand': 'Run:',
    'migrations.viewDetails': 'View Details',
    'users.title': 'User Management',
    'users.subtitle': 'Manage user accounts and permissions',
    'users.addUser': 'Add User',
    'users.export': 'Export',
    'users.stats.title': 'User Statistics',
    'users.stats.totalUsers': 'Total Users',
    'users.stats.activeUsers': 'Active Users',
    'users.stats.administrators': 'Administrators',
    'users.stats.activeThisWeek': 'Active This Week',
    'users.filters.searchPlaceholder': 'Search users...',
    'users.filters.role': 'Role',
    'users.filters.allRoles': 'All Roles',
    'users.filters.status': 'Status',
    'users.filters.allUsers': 'All Users',
    'users.filters.clearFilters': 'Clear Filters',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.lastLogin': 'Last Login',
    'users.created': 'Created',
    'users.actions.deactivate': 'Deactivate user',
    'users.actions.activate': 'Activate user',
    'users.actions.toggleStatus': 'Toggle User Status',
    'users.actions.toggleStatusConfirm': 'Are you sure you want to activate/deactivate this user?',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.messages.noUsers': 'No users found',
    'users.editTitle': 'Edit User',
    'users.form.saveChanges': 'Save Changes',
    'users.form.basicInformation': 'Basic Information',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.phone': 'Phone',
    'users.bio': 'Bio',
    'users.form.accountStatus': 'Account Status',
    'users.form.accountActive': 'Account Active',
    'users.form.accountActiveHelp': 'User can sign in and access the system',
    'users.form.emailVerified': 'Email Verified',
    'users.form.emailVerifiedHelp': 'User has verified their email address',
    'users.form.userDetails': 'User Details',
    'users.form.userId': 'User ID',
    'users.form.status': 'Status',
    'users.form.security': 'Security',
    'users.form.twoFactorEnabled': '2FA Enabled',
    'users.dangerZone.title': 'Danger Zone',
    'users.dangerZone.subtitle': 'Irreversible and destructive actions',
    'users.dangerZone.hardDelete': 'Hard Delete (Permanent)',
    'users.dangerZone.hardDeleteHelp': 'Permanently remove from database. Unchecked performs soft delete (deactivate only).',
    'users.dangerZone.deleteButton': 'Delete User',
    'users.dangerZone.deleteConfirm': 'Are you sure you want to delete this user? Check the "Hard Delete" option to permanently remove all data from the database. This action cannot be undone!',
    'users.delete': 'Delete User',
    'users.roles.admin': 'Administrator',
    'users.roles.editor': 'Editor',
    'users.roles.author': 'Author',
    'users.roles.viewer': 'Viewer',
    'common.search': 'Search',
    'common.actions': 'Actions',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.yes': 'Yes'
  };
  return (key: string, params?: Record<string, any>) => {
    let text = translations[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };
}